version: '3.5'
services:

        #Laravel App
        app:
                build:
                        context: .
                        dockerfile: Dockerfile
                image: codemonkey076/laravel
                container_name: app
                restart: unless-stopped
                depends_on:
                        - db
                        - redis
                tty: true
                environment:
                        SERVICE_NAME: app
                        SERVICE_TAGS: dev
                working_dir: /var/www/html
                volumes:
                        - ./:/var/www/html
                networks:
                        - helpdesk

        # NGINX Web Server
        nginx:
                image: nginx:alpine
                container_name: nginx
                restart: unless-stopped
                depends_on:
                        - app
                        - websockets
                tty: true
                ports:
                        - 80:80
                        - 443:443
                volumes:
                        - ./:/var/www/html
                        - ./nginx/sites/app.prod.conf:/etc/nginx/conf.d/app.prod.conf
                        - ./nginx/sites/websockets.prod.conf:/etc/nginx/conf.d/websockets.prod.conf
                        - ./nginx/ssl/:/etc/nginx/ssl/
                networks:
                        - helpdesk

        # MySQL Service
        db:
                image: mysql:5.7
                container_name: db
                restart: unless-stopped
                tty: true
                ports:
                        - 3306:3306
                environment:
                        MYSQL_DATABASE: laraveldb
                        MYSQL_USER: laravel
                        MYSQL_PASSWORD: secret
                        MYSQL_ROOT_PASSWORD: secret
                volumes:
                        - mysqldata:/var/lib/mysql/
                networks:
                        - helpdesk
                          
        # Redis Server
        redis:
                image: redis:6-alpine
                container_name: redis
                restart: unless-stopped
                ports:
                        - 6379:6379
                networks:
                        - helpdesk

        # Elastic Search Service
        elasticsearch:
                image: elasticsearch:7.10.1
                container_name: elasticsearch
                volumes:
                        - esdata:/usr/share/elasticsearch/data
                environment:
                        - discovery.type=single-node
                ports:
                        - 9200:9200
                        - 9300:9300
                networks:
                        - helpdesk

        # Websockets Server
        websockets:
                image: codemonkey076/laravel:1.0.0
                container_name: websockets
                depends_on:
                        - app
                restart: unless-stopped
                ports:
                        - 6001:6001
                volumes:
                        - .:/var/www
                command: php /var/www/artisan websockets:serve
                networks:
                        - helpdesk


        # Horizon Server
        horizon:
                image: codemonkey076/laravel:1.0.0
                container_name: horizon
                depends_on:
                        - app
                restart: unless-stopped
                volumes:
                        - .:/var/www
                command: php /var/www/artisan horizon
                networks:
                        - helpdesk

        # Mailhog
        mailhog:
                image: mailhog/mailhog:latest
                container_name: mailhog
                restart: unless-stopped
                ports:
                        - 8025:8025
                networks:
                        - helpdesk

# Docker networks
networks:
        helpdesk:
                driver: bridge
                        
# Volumes
volumes:
        mysqldata:
        esdata:
